### ISSUE TITLE
Getting "invalid parameter" when passing plugin-specific params

### ISSUE THREAD

**Issue by aidanalphafund** [Tuetuopay/protoc-gen-prost#2]
First off, thank you for getting this library out, it's a huge help!

## Problem
All of the custom [protoc-gen-prost](https://github.com/Tuetuopay/protoc-gen-prost#options-specific-to-the-plugin) params fail with the message "invalid parameter".

Params [inherited from prost_build](https://github.com/Tuetuopay/protoc-gen-prost#options-inherited-from-prost_build) such as `type_attribute` are working correctly.

#### example.proto
```protobuf
syntax = "proto3";

package example;

message Thing {
    string name = 1;
    string payload = 2;
}
```

#### Successful Command
This command successfully generates an `example.rs` file:
```shell
protoc --prost_out=hello-rs -I . example.proto
```

#### Failed Command
This command fails with the error `--prost_out: invalid parameter: include_file`
```shell
protoc --prost_out=hello-rs -I . example.proto --prost_opt=include_file
```

**Comment by Tuetuopay** [comment]
Hi! How did you install `protoc-gen-prost`? If you did through crates.io then this is not the proper repository. The one actually published on crates.io is [this one](https://github.com/neoeinstein/protoc-gen-prost). See #1 for more details.

**Comment by aidanalphafund** [comment]
That was the problem, thanks @Tuetuopay!
